# Generated by Django 4.2.11 on 2025-10-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='auto_delete_at',
            field=models.DateTimeField(blank=True, help_text="Date d'auto-suppression", null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('payment_success', 'Paiement reçu'), ('payment_failed', 'Paiement échoué'), ('subscription_overdue', 'Abonnement en retard'), ('subscription_suspended', 'Compte suspendu'), ('trip_update', 'Mise à jour de trajet'), ('sos_alert', 'Alerte SOS'), ('admin_message', 'Message admin'), ('chat_message', 'Message de chat'), ('trip_confirmation', 'Confirmation de course')], max_length=64),
        ),
    ]
