# Generated by Django 4.2.11 on 2025-11-17 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0008_riderequest_chauffeur_archived_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], help_text='Note de 1 à 5 étoiles')),
                ('was_on_time', models.BooleanField(blank=True, help_text="Est arrivé(e) à l'heure ?", null=True, verbose_name="À l'heure")),
                ('was_polite', models.BooleanField(blank=True, help_text='A été courtois(e) et respectueux(se) ?', null=True, verbose_name='Courtois(e)')),
                ('was_safe', models.BooleanField(blank=True, help_text='Conduite sûre et confortable ? (pour chauffeur)', null=True, verbose_name='Conduite sûre')),
                ('vehicle_clean', models.BooleanField(blank=True, help_text='Véhicule propre et en bon état ? (pour chauffeur)', null=True, verbose_name='Véhicule propre')),
                ('comment', models.TextField(blank=True, help_text='Commentaire optionnel (max 500 caractères)', max_length=500, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subscriptions.trip')),
            ],
            options={
                'verbose_name': 'Évaluation de trajet',
                'verbose_name_plural': 'Évaluations de trajets',
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'rater', 'rated')},
            },
        ),
    ]
