# Generated by Django 4.2.11 on 2025-09-27 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=9)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('overdue', 'En retard'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='active', max_length=32)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active_child_name', models.CharField(blank=True, max_length=128)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('dropoff_location', models.CharField(blank=True, max_length=255)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=9)),
                ('trips_per_day', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('average_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shared_tracking_url', models.URLField(blank=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_trips', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-scheduled_date', '-started_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_suggestion', models.CharField(blank=True, max_length=64)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='subscriptions.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_initiated', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_type', models.CharField(choices=[('en_route', 'En route'), ('arrived', 'Arrivé'), ('child_picked', 'Enfant récupéré'), ('child_dropped', 'Enfant déposé'), ('completed', 'Terminé'), ('issue', 'Incident')], max_length=32)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='subscriptions.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
