# Generated by Django 4.2.11 on 2025-09-28 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_alter_trip_scheduled_date_alter_trip_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='accept_shared_ride',
            field=models.BooleanField(default=False, verbose_name='Accepte trajet partagé'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude destination'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude destination'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='max_distance_km',
            field=models.PositiveIntegerField(default=10, help_text='Rayon de recherche des chauffeurs', verbose_name='Distance maximale (km)'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='min_rating',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Note minimale requise'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='need_child_seat',
            field=models.BooleanField(default=False, verbose_name='Siège enfant requis'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude départ'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude départ'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='priority',
            field=models.CharField(choices=[('closest', 'Le plus proche'), ('fastest', 'Le plus rapide'), ('best_rated', 'Le mieux noté'), ('cheapest', 'Le moins cher')], default='closest', max_length=20, verbose_name='Critère de priorité'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='chauffeur',
            field=models.ForeignKey(blank=True, help_text="Chauffeur assigné lors de l'acceptation", limit_choices_to={'role': 'chauffeur'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='dropoff_location',
            field=models.CharField(max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Instructions particulières'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_location',
            field=models.CharField(max_length=255, verbose_name='Point de départ'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='requested_pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure souhaitée'),
        ),
    ]
