# Generated by Django 4.2.11 on 2025-09-28 19:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_riderequest_accept_shared_ride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChauffeurSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.TimeField()),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('specific_days', models.JSONField(blank=True, default=list)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=9)),
                ('child_name', models.CharField(blank=True, max_length=100)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('payment_pending', 'Paiement en attente'), ('active', 'Actif'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='payment_pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('parent_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('chauffeur_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement chauffeur',
                'verbose_name_plural': 'Abonnements chauffeur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobilityPlusSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('next_billing_date', models.DateField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Prix mensuel en FCFA', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobility_plus_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement Mobility Plus',
                'verbose_name_plural': 'Abonnements Mobility Plus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('mobility_plus', 'Mobility Plus'), ('chauffeur_subscription', 'Abonnement Chauffeur')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chauffeur_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.chauffeursubscription')),
                ('mobility_plus_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.mobilityplussubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnements",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChauffeurSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la demande (ex: Transport scolaire matin/soir)', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée des besoins')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.TimeField(help_text='Heure de départ souhaitée')),
                ('return_time', models.TimeField(blank=True, help_text='Heure de retour (optionnel)', null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekdays', 'Jours de semaine'), ('weekly', 'Hebdomadaire'), ('custom', 'Personnalisé')], default='weekdays', max_length=20)),
                ('specific_days', models.JSONField(blank=True, default=list, help_text='Jours spécifiques si fréquence personnalisée (format: [1,2,3,4,5] pour lun-ven)')),
                ('proposed_price_monthly', models.DecimalField(decimal_places=2, help_text='Prix mensuel proposé en FCFA', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('10000.00'))])),
                ('child_name', models.CharField(blank=True, help_text="Nom de l'enfant (optionnel)", max_length=100)),
                ('special_requirements', models.TextField(blank=True, help_text='Exigences spéciales (siège enfant, climatisation, etc.)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('payment_pending', 'Paiement en attente'), ('active', 'Actif'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration de la demande")),
                ('chauffeur_response', models.TextField(blank=True)),
                ('chauffeur_counter_offer', models.DecimalField(blank=True, decimal_places=2, help_text='Contre-proposition du chauffeur', max_digits=9, null=True)),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'chauffeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'abonnement chauffeur",
                'verbose_name_plural': "Demandes d'abonnement chauffeur",
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'chauffeur', 'status')},
            },
        ),
        migrations.AddField(
            model_name='chauffeursubscription',
            name='subscription_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscription', to='subscriptions.chauffeursubscriptionrequest'),
        ),
    ]
