# Generated by Django 4.2.11 on 2025-09-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_chauffeursubscription_mobilityplussubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilityplussubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('overdue', 'En retard'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='active', max_length=32),
        ),
    ]
