# Generated by Django 4.2.11 on 2025-10-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_trip_user_archive_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='chauffeur_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='parent_archived',
            field=models.BooleanField(default=False),
        ),
    ]
