# Generated by Django 4.2.11 on 2025-09-27 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeurprofile',
            name='active_badges',
            field=models.ManyToManyField(blank=True, related_name='chauffeurs', through='accounts.ChauffeurBadge', to='core.badge'),
        ),
        migrations.AddField(
            model_name='chauffeurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chauffeurbadge',
            name='awarded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chauffeurbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge'),
        ),
        migrations.AddField(
            model_name='chauffeurbadge',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chauffeurprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='chauffeurbadge',
            unique_together={('chauffeur', 'badge')},
        ),
    ]
