# Generated by Django 4.2.11 on 2025-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Particulier'), ('chauffeur', 'Chauffeur'), ('admin', 'Admin')], default='parent', max_length=32),
        ),
    ]
