# Generated by Django 4.2.11 on 2025-09-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeurprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude actuelle'),
        ),
        migrations.AddField(
            model_name='chauffeurprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude actuelle'),
        ),
        migrations.AddField(
            model_name='chauffeurprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible pour une course'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration du permis'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4, verbose_name='Score de fiabilité'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis"),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=32, verbose_name='Couleur du véhicule'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=64, verbose_name='Marque du véhicule'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=64, verbose_name='Modèle du véhicule'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=32, verbose_name='Immatriculation'),
        ),
        migrations.AlterField(
            model_name='chauffeurprofile',
            name='zone',
            field=models.CharField(blank=True, max_length=64, verbose_name="Zone d'activité"),
        ),
    ]
